version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-redux
    versions:
    - 7.2.3
    - 7.2.4
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.8.1
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.13
    - 13.0.16
    - 13.0.7
    - 13.0.8
    - 13.1.1
    - 13.1.2
    - 13.1.5
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: react-scripts
    versions:
    - 4.0.3
